name: merge and release

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

      - uses: actions/checkout@v3

      - name: show current branch
        run: |
          echo current branch `git rev-parse --abbrev-ref HEAD`

      - name: Run GH CLI
        run: gh release create test
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          ref: 'develop'

      - name: Merge branch
        run: |
          echo "github.ref = ${{ github.ref }}"
          echo current branch `git rev-parse --abbrev-ref HEAD`
          git fetch --unshallow
          git pull
          git merge --no-ff develop -m "Auto-merge back to develop branch"
          git push
        env:
          GITHUB_TOKEN: ${{ github.token }}