name: merge and release

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

      - uses: actions/checkout@v3

      # - name: Run GH CLI
      #   run: gh release create test
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      
      - name: Create PR
        run: gh pr create
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Merge branch
        run: gh pr merge develop
        env:
          GITHUB_TOKEN: ${{ github.token }}