name: merge and release

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Run GH CLI
        run: gh release create test